outputFilename:
outputDirectory: target/proto
includeMessageDocs: true
includeFieldDocs: true
includeSourceLocationInDoc: true
inheritanceToComposition: true
includeValidationRules: false
customImports:
  - google/protobuf/timestamp.proto
  - google/protobuf/duration.proto
customImportLocations:
  - target/proto_deps
customTypeMappings:
  ^duration$ : google.protobuf.Duration
  ^dateTime$ : google.protobuf.Timestamp
  ^time$: google.protobuf.Timestamp
  ^timestamp$: google.protobuf.Timestamp

customNameMappings:

ignoreOutputFields:
  - uk.org.ifopt.www.ifopt/PointProjectionStructure/Coordinates
  - uk.org.ifopt.www.ifopt/PlaceEquipmentStructure/EquipmentName
  - uk.org.ifopt.www.ifopt/AbstractEquipmentStructure/EquipmentName
  - uk.org.ifopt.www.ifopt/InstalledEquipmentStructure/EquipmentName
  - uk.org.ifopt.www.ifopt/LocalServiceStructure/EquipmentName
  - uk.org.ifopt.www.ifopt/FeatureRefsType/FeatureRef
  - eu.datex2.schema._2_0rc1._2_0/TpegDescriptor/descriptor

options:
  java_multiple_files : true
